### ISSUE TITLE
Finish decoupling from Oscar

### ISSUE THREAD

**Issue by carver** [carver/django-account-balances#1]
The primary goal of the fork is still unfinished.

**Comment by carver** [comment]
decoupled, and basic use case tested.

**Comment by Leeibrah** [comment]
Hi, Thanks for the repo. My issue is that it still requires oscar. Getting the error No module named oscar when I try to run any ./manage.py command.
Do I need oscar to run this repo?

**Comment by carver** [comment]
I seem to remember that if you install the other version first, then it installs other packages that depend on oscar.  Try a fresh install.  Also my changes aren't in master, so be sure you're using the branch `remove-oscar`.

**Comment by Leeibrah** [comment]
Thanks for reply but the remove-oscar branch still requires oscar. Even tried cloning(fresh install) to a different machine - same problem.
Any other idea how I could overcome this?

**Comment by carver** [comment]
The only suggestion I have is to follow the stack trace from `No module named oscar` and see how hard it is to remove or replace the reference.

I'm not actively using or maintaining this project, so unfortunately that's about all the help I can give.
